import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { PUBLIC_PATHS } from "../src/lib/site.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

async function collectFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const groups = await Promise.all(entries.map((entry) => {
    const location = path.join(directory, entry.name);
    return entry.isDirectory() ? collectFiles(location) : Promise.resolve([location]);
  }));
  return groups.flat().sort();
}

const hash = createHash("sha256");
for (const file of await collectFiles(path.join(root, "src"))) {
  hash.update(path.relative(root, file));
  hash.update(await readFile(file));
}
hash.update(await readFile(path.join(root, "package-lock.json")));
hash.update(await readFile(path.join(root, "next.config.ts")));
hash.update(await readFile(path.join(root, "public/offline.html")));
hash.update(await readFile(path.join(root, "scripts/build-service-worker.ts")));
for (const directory of ["icons", "brand", "samples"]) {
  const location = path.join(root, "public", directory);
  if (!existsSync(location)) continue;
  for (const file of await collectFiles(location)) {
    hash.update(path.relative(root, file));
    hash.update(await readFile(file));
  }
}

const productionAssets = process.argv.includes("--production-assets")
  ? [...(await collectFiles(path.join(root, ".next/static")))
      .filter((file) => /\.(?:js|css|woff2?|ttf|otf)$/.test(file))
      .map((file) => `/_next/static/${path.relative(path.join(root, ".next/static"), file).split(path.sep).join("/")}`),
      "/samples/still-life-original.jpg", "/samples/still-life-optimized.webp"]
  : [];
hash.update(JSON.stringify(productionAssets));
const version = hash.digest("hex").slice(0, 16);
const source = (await readFile(path.join(root, "src/workers/service-worker.ts"), "utf8"))
  .replaceAll("__SW_VERSION__", version)
  .replace('["__PUBLIC_ROUTES__"]', JSON.stringify(["/app", ...PUBLIC_PATHS]))
  .replace('["__PRECACHE_ASSETS__"]', JSON.stringify(productionAssets));
const compiled = ts.transpileModule(source, {
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None, removeComments: true },
});
await writeFile(path.join(root, "public/sw.js"), `// Generated by scripts/build-service-worker.ts. Edit the TypeScript source.\n${compiled.outputText}`);
console.log(`Built ShrinkFox service worker ${version} (${productionAssets.length} production assets)`);
