/** Rebuild the landing comparison from the real browser compressor. Requires a running app. */
import { chromium, expect } from "@playwright/test";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const executablePath =
  process.env.CHROME_PATH ??
  [
    "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  ].find(existsSync);
const browser = await chromium.launch({
  ...(executablePath ? { executablePath } : {}),
  headless: true,
});
try {
  const page = await browser.newPage({
    viewport: { width: 1440, height: 1000 },
  });
  await page.goto(`${process.env.E2E_BASE ?? "http://localhost:3000"}/app`);
  await page.waitForLoadState("networkidle");
  await page
    .locator('input[type="file"]')
    .first()
    .setInputFiles(resolve("public/samples/still-life-original.jpg"));
  await expect(page.getByLabel("Output format", { exact: true })).toBeVisible();
  await expect(
    page
      .getByLabel("Output format", { exact: true })
      .locator('option[value="webp"]'),
  ).toBeEnabled();
  await page.getByLabel("Output format", { exact: true }).selectOption("webp");
  await page.getByRole("radio", { name: "Quality", exact: true }).click();
  await page.getByRole("button", { name: "Start", exact: true }).click();
  const preview = page.getByRole("button", {
    name: "Preview still-life-original.jpg",
    exact: true,
  });
  await expect(preview).toBeVisible({ timeout: 60_000 });
  const downloadEvent = page.waitForEvent("download");
  await page
    .getByRole("button", {
      name: "Download still-life-original.jpg",
      exact: true,
    })
    .click();
  const download = await downloadEvent;
  await download.saveAs(resolve("public/samples/still-life-optimized.webp"));
  const bytes = await readFile(
    resolve("public/samples/still-life-optimized.webp"),
  );
  const original = await readFile(
    resolve("public/samples/still-life-original.jpg"),
  );
  const savedPercent = Math.round((1 - bytes.length / original.length) * 100);
  const label = (length: number) => `${(length / 1000).toFixed(1)} KB`;
  await writeFile(
    resolve("src/lib/api/showcase.ts"),
    `// Generated by scripts/generate-showcase.ts through the browser image engine.\nexport const SHOWCASE = ${JSON.stringify({ originalLabel: label(original.length), outputLabel: label(bytes.length), savedPercent })} as const;\n`,
  );
  console.log(
    `Real sample conversion: ${label(original.length)} to ${label(bytes.length)} (${savedPercent}% smaller).`,
  );
} finally {
  await browser.close();
}
